### PR TITLE
fix(nntp): Skip failing usenet providers with circuit breaker

### LINKED ISSUE #282: Failing backup provider causes all downloads to fail with "CouldNotLoginToUsenetException"
**Describe the bug**
Downloads were failing at 0% with authentication timeouts in the logs. They would fail, return to "queued", and the process repeats endlessly. The issue was caused by a single backup provider (Vipernews) that was failing to authenticate. Once disabled, the connection pool errors ceased, and downloads resumed. Although it was configured as a backup (not primary), its failures caused every queued download to fail and return to queued status. This was easy to miss, as I have quite a few providers, and the issue was only discovered after I manually tested each connection.

**To Reproduce**
Unsure if this can be reproduced - you cannot manually add a failing provider. Potentially;
- set up two providers in nzbdav
- change your password with one of the providers
- attempt to download an NZB
- Watch as all downloads fail at 0%

**Expected behavior**
A failing backup provider should be skipped/de-prioritized, allowing downloads to proceed using healthy primary and backup providers. Perhaps error logging, or a notification in the UI to indicate the failures.

**Workaround**
Disable the failing backup provider. Downloads proceed normally with remaining healthy providers.

**Additional context**
Logdump:
```
[20:31:31  WRN ] Error getting connection-lock.
NzbWebDAV.Exceptions.CouldNotLoginToUsenetException: Could not login to usenet host.
 ---> System.TimeoutException: Timeout reading from NNTP stream.
   at UsenetSharp.Clients.UsenetClient.ReadLineAsync(CancellationToken ct)
   at UsenetSharp.Clients.UsenetClient.AuthenticateAsync(String user, String pass, CancellationToken cancellationToken)
   at NzbWebDAV.Clients.Usenet.BaseNntpClient.AuthenticateAsync(String user, String pass, CancellationToken cancellationToken) in /backend/Clients/Usenet/BaseNntpClient.cs:line 43
   --- End of inner exception stack trace ---
   at NzbWebDAV.Clients.Usenet.BaseNntpClient.AuthenticateAsync(String user, String pass, CancellationToken cancellationToken) in /backend/Clients/Usenet/BaseNntpClient.cs:line 54
   at NzbWebDAV.Clients.Usenet.UsenetStreamingClient.CreateNewConnection(ConnectionDetails connectionDetails, CancellationToken ct) in /backend/Clients/Usenet/UsenetStreamingClient.cs:line 92
   at NzbWebDAV.Clients.Usenet.Connections.ConnectionPool`1.GetConnectionLockAsync(SemaphorePriority priority, CancellationToken cancellationToken)
   at NzbWebDAV.Clients.Usenet.MultiConnectionNntpClient.RunWithConnection[T](String name, SemaphorePriority priority, Fun`3 command, Action`1 onConnectionReadyAgain, CancellationToken ct, Int32 retryCount) in /backend/Clients/Usenet/MultiConnectionNntpClient.cs:line 149
```
----

**NOTE:**
**NZBDAV is intended for use with legally obtained content only. The project maintainers do not condone piracy and will not provide support for users suspected of engaging in copyright infringement. Issues related to or suspected of piracy will be closed.**

### PR DESCRIPTION
**Pull request by hoivikaj**
### Problem

When a usenet provider fails to authenticate (e.g. changed password, expired account, provider outage), every NNTP operation still attempts that provider first. Each failed attempt burns ~40 seconds waiting for UsenetSharp's internal read timeout, and with 1 retry that's ~80 seconds wasted per segment before falling through to the next provider.

For downloads with hundreds of segments, this means the download stalls at 0% and gets re-queued endlessly - even though other healthy providers are available and could serve the content. This affects both pooled and backup providers equally: one misbehaving provider brings the entire pipeline down.

### Solution

Add a `ProviderCircuitBreaker` to each provider that tracks consecutive connection failures and temporarily removes the provider from the rotation when a failure threshold is reached.

**Circuit breaker behavior:**
- **Threshold:** 3 consecutive failures to trip
- **Initial cooldown:** 60 seconds (doubles on repeated trips, capped at 5 minutes)
- **Probe:** after cooldown expires, one attempt is allowed - success resets the breaker, failure re-trips with longer cooldown
- **Logging:** warns when a provider trips, logs when it recovers

`MultiProviderNntpClient.GetOrderedProviders()` now filters out tripped providers, so healthy providers handle traffic immediately. If all providers are tripped, the full list is returned so cooldown probes can still fire.

### Changes

- **New:** `ProviderCircuitBreaker` - tracks consecutive failures, manages trip/cooldown/probe lifecycle
- **Modified:** `MultiConnectionNntpClient` - records success/failure on the circuit breaker after each operation
- **Modified:** `MultiProviderNntpClient` - skips tripped providers in `GetOrderedProviders()`
- **Modified:** `UsenetStreamingClient` - creates a `ProviderCircuitBreaker` per provider (identified by host name)

Fixes #282

### CODE REVIEW

File: backend/Clients/Usenet/Connections/ProviderCircuitBreaker.cs [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+                if (_trippedUntilMs == 0) return false;
+                if (Environment.TickCount64 >= _trippedUntilMs)
+                {
+                    // Cooldown expired — allow a probe attempt
+                    return false;
+                }
+                return true;
+            }
+        }
+    }
```
Comment (nzbdav-dev) [inline backend/Clients/Usenet/Connections/ProviderCircuitBreaker.cs:42]: We can remove the lock on this method :)

```suggestion
    public bool IsTripped
    {
        get
        {
            var trippedUntil = Volatile.Read(ref _trippedUntilMs);
            if (trippedUntil == 0) return false;
            return Environment.TickCount64 < trippedUntil;
        }
    }
```

**Review by nzbdav-dev — COMMENTED** [review]
Ty for the PR, looks good to me! 
One minor comment.
